#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    case "$1" in
        remove|deconfigure)
            systemctl stop vidwatcher.service || true
            systemctl disable vidwatcher.service || true
            ;;
    esac
fi

exit 0
